# Generated by Django 4.1.7 on 2023-03-07 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ManyToManyField(
                related_name="books",
                through="followings.Following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
