# Generated by Django 4.1.7 on 2023-03-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.CharField(max_length=5),
        ),
    ]
