# Generated by Django 4.1.7 on 2023-03-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="user",
            new_name="users",
        ),
    ]
