# Generated by Django 4.1.7 on 2023-03-06 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="isbn",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxLengthValidator(13),
                    django.core.validators.MinLengthValidator(13),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="copy",
            name="pages",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(5)]
            ),
        ),
    ]
