# Generated by Django 4.1.7 on 2023-03-07 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0002_copy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="user",
            field=models.ManyToManyField(
                related_name="current_books",
                through="loans.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
