# Generated by Django 4.1.7 on 2023-03-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="isbn",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
