# Generated by Django 4.1.7 on 2023-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0003_alter_copy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="isbn",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="copy",
            name="pages",
            field=models.CharField(max_length=5),
        ),
    ]
