# Generated by Django 4.1.7 on 2023-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copies", "0004_alter_copy_isbn_alter_copy_pages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="user",
            new_name="users",
        ),
        migrations.AlterField(
            model_name="copy",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
